# Generated by Django 4.2.5 on 2023-09-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms_app', '0002_tasks_remove_team_members_team_password_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
